jobs:
  include:
  - stage: GitHub Release
    script: bash scripts/build.sh
    deploy:
      provider: releases
      api_key:
        secure: A17in31e6wG6XOBPwq2Xg/rC/8GHRUlEBrFfQlzi0YGLZ+GzNLWszG83qt6KI55vd8cmHex9IiJhQsxkUTe5Rv8DAY/epqmEhjiIZO7oI2BLNYZXZOUCA83La8KezhrAGCjiIqLZ+fFPvJnQxfveYv8vOvHa18AbzGY2CdTWwYeNI2egQogMWyOHL2sibSXTQ0Wl24ytQlgtb6OfcyHjwzVzEcAN9GAECiTrCWWo2lFOGHFErDaEnQmCt++6w106HD+FTV9+Ck+OhJTAYkBSiMBvYiEWhqA1bi39d4pTQsFrPfOutaHhSj0/lqC7bF1deLy87u7rEFMjCw4cFVqpsCmMp0+p6irsHGvO6apX74nukBoGXCyyL1kuasJAbZDQmRy2XlDmIhXAjX+0mfocRRmJT9/lv+jnHHJ9MbMIR4Tuu4xHLdfQMUAA4fExINiX0gX658p9f2shPINsENSD0dtoWo4g9voc+pa5zPIChdWXm29sShtBDHy4LOVhegLkTbygJabSfPU6OP2k70bv8ZCmJ8p6Aq+/qZDYGCv9LKkB+EfqdCZmtuXje6yoU1tQ++2KzoAFX9trnW87ietx+cYEaW7c1qh+TdckiXgtlycmlP8bJ+Ecjz4spxjzb+4w6Z/wFBe+Jh2YfjodP1UMANSV7Kz8JLevfagjDfKMJlg=
      file:
      - release.zip
      - release.tgz
      skip_cleanup: true
      on:
        tags: true